INSERT INTO pets (CATEGORY_ID, NAME, PHOTO_URL_ID, TAGS_ID, STATUS)
VALUES(1, 'ポチ', 1, 1, 1);


INSERT INTO category (CATEGORY)
VALUES('犬');
INSERT INTO category (CATEGORY)
VALUES('猫');
INSERT INTO category (CATEGORY)
VALUES('ハムスター');

INSERT INTO photoURL (PHOTO_URL)
VALUES('url1');
INSERT INTO photoURL (PHOTO_URL)
VALUES('url2');
INSERT INTO photoURL (PHOTO_URL)
VALUES('url3');

INSERT INTO tags (TAGS)
VALUES('tag1');
INSERT INTO tags (TAGS)
VALUES('tag2');
INSERT INTO tags (TAGS)
VALUES('tag3');