DROP TABLE IF EXISTS pets;
CREATE TABLE pets (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHOTO_URL_ID INT NOT NULL,
    TAGS_ID INT NOT NULL,
    STATUS INT NOT NULL
);
CREATE TABLE category
(
   CATEGORY_ID int PRIMARY KEY AUTO_INCREMENT,
   CATEGORY VARCHAR (100)
);
CREATE TABLE photoURL
(
   PHOTO_URL_ID int PRIMARY KEY AUTO_INCREMENT,
   PHOTO_URL VARCHAR (255)
);
CREATE TABLE tags
(
   TAGS_ID int PRIMARY KEY AUTO_INCREMENT,
   TAGS VARCHAR (100)
);

